"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { cn } from "@/lib/utils";
import { CountUpNumber } from "@/components/shared/count-up-number";
import { usePrefersReducedMotion } from "@/components/shared/use-media-query";

/**
 * Scroll-driven journey map — the centrepiece "you are riding the campaign"
 * moment. A route line draws itself as the section scrolls through the
 * viewport, with each funded mile lighting up as the draw head passes it.
 *
 * Design notes:
 *
 * - The route is an SVG <path> whose dash offset is driven by a scroll
 *   listener (rAF-throttled) rather than by CSS scroll-timeline. Two reasons:
 *   `animation-timeline: scroll()` still isn't in Safari, and the same
 *   progress value has to drive the mile markers, the readout panel and the
 *   line itself, so a single JS source of truth is simpler than coordinating
 *   an animation with DOM reads.
 *
 * - The path is decorative, so it's aria-hidden and the accessible
 *   equivalent (a plain funded/remaining summary) is rendered as real text
 *   alongside it.
 *
 * - Mile positions come from ROUTE as normalized (x, y) in a 0..1 viewBox
 *   space, then get projected. That keeps the geometry independent of the
 *   rendered pixel size, so it works at any width without a resize handler.
 */

interface RoutePoint {
  /** The real mile number, 1-based — shown in the readout. */
  number: number;
  /** Cumulative fraction along the route where this mile sits, 0..1. */
  at: number;
  /** Funds raised toward this mile's goal. */
  raised: number;
  goal: number;
  status: "available" | "requested" | "reserved" | "partially_funded" | "funded";
  /** Dedication text ("In memory of …") when a donor attached one. */
  dedication: string | null;
}

/**
 * The route as an SVG path in a 100x100 viewBox. Coordinates are hand-placed
 * to read as a road climbing away from the viewer toward a finish — the
 * "up and over then down" shape of a point-to-point triathlon, which is what
 * the actual Chattanooga course does. Mile markers are generated by sampling
 * along this path (see samplePath below) rather than hand-placed, so adding
 * or removing a mile can never desync a marker from the line.
 */
const ROUTE_D = "M 6,88 C 18,86 22,74 30,70 C 40,65 44,52 52,48 C 60,44 64,32 70,30 C 78,27 84,18 92,14";
const VIEWBOX = 100;

/** Status → the visual weight a mile gets. Funded is the only "lit" state. */
const STATUS_RADIUS: Record<RoutePoint["status"], number> = {
  available: 1.1,
  requested: 1.3,
  reserved: 1.5,
  partially_funded: 1.7,
  funded: 2.1,
};

/**
 * Samples a cubic-Bezier path at t, returning the point. Only the first M and
 * a run of C commands are supported, which is all ROUTE_D uses — a full path
 * parser isn't worth it for a fixed decorative route, and silently
 * mis-parsing would be worse than a clearly-scoped helper.
 */
function samplePath(d: string, t: number): { x: number; y: number } {
  const nums = d.match(/-?\d+(\.\d+)?/g);
  if (!nums || nums.length < 2) return { x: 0, y: 0 };
  const start = { x: Number(nums[0]), y: Number(nums[1]) };
  // Each C contributes 6 numbers: c1x c1y c2x c2y x y.
  const curves: { c1: [number, number]; c2: [number, number]; end: [number, number] }[] = [];
  for (let i = 2; i + 5 < nums.length; i += 6) {
    curves.push({
      c1: [Number(nums[i]), Number(nums[i + 1])],
      c2: [Number(nums[i + 2]), Number(nums[i + 3])],
      end: [Number(nums[i + 4]), Number(nums[i + 5])],
    });
  }
  if (curves.length === 0) return start;

  const scaled = t * curves.length;
  const index = Math.min(Math.floor(scaled), curves.length - 1);
  const local = scaled - index;
  const { c1, c2, end } = curves[index];
  // Every curve segment starts where the previous one ended; the first starts
  // at the M coordinate. Normalized to a tuple so the Bezier below indexes
  // consistently regardless of which one it is.
  const from: [number, number] = index === 0 ? [start.x, start.y] : curves[index - 1].end;

  // Cubic Bezier at local t.
  const u = 1 - local;
  return {
    x: u ** 3 * from[0] + 3 * u ** 2 * local * c1[0] + 3 * u * local ** 2 * c2[0] + local ** 3 * end[0],
    y: u ** 3 * from[1] + 3 * u ** 2 * local * c1[1] + 3 * u * local ** 2 * c2[1] + local ** 3 * end[1],
  };
}

export function JourneyMap({
  miles,
  totalRaised,
  goal,
  className,
}: {
  miles: RoutePoint[];
  totalRaised: number;
  goal: number;
  className?: string;
}) {
  const sectionRef = useRef<HTMLElement>(null);
  /** Raw scroll progress, 0..1. Always 0 when reduceMotion is true. */
  const [scrollProgress, setScrollProgress] = useState(0);
  const [pathLength, setPathLength] = useState(1);
  const reduceMotion = usePrefersReducedMotion();

  // Under reduced motion the route is simply always drawn — a static, complete
  // map is both the accessible end state and the more useful one to read.
  const progress = reduceMotion ? 1 : scrollProgress;

  // Measure the real path length so the dash math is in path units, not
  // guessed. getTotalLength is DOM-only, so it has to happen after mount.
  useEffect(() => {
    const path = sectionRef.current?.querySelector("path[data-route-line]") as SVGPathElement | null;
    if (!path) return;
    const len = path.getTotalLength();
    if (len > 0) setPathLength(len);
  }, []);

  useEffect(() => {
    const el = sectionRef.current;
    // Reduced motion / no-JS: the listener never attaches and `progress` stays
    // 0, which would leave the route undrawn. Derive the full value instead of
    // setState-ing in the effect — see the `progress` derivation below.
    if (!el || reduceMotion) return;

    let frame = 0;
    const update = () => {
      frame = 0;
      const rect = el.getBoundingClientRect();
      // Travel the route across the middle 80% of the section's pass through
      // the viewport, so the line isn't already finished when it appears and
      // isn't still drawing after it leaves.
      const total = rect.height + window.innerHeight;
      const travelled = window.innerHeight - rect.top;
      const raw = (travelled - window.innerHeight * 0.1) / (total - window.innerHeight * 0.9);
      const next = Math.min(Math.max(raw, 0), 1);
      setScrollProgress(next);
    };

    const onScroll = () => {
      if (frame) return;
      frame = requestAnimationFrame(update);
    };

    update();
    window.addEventListener("scroll", onScroll, { passive: true });
    window.addEventListener("resize", onScroll, { passive: true });
    return () => {
      if (frame) cancelAnimationFrame(frame);
      window.removeEventListener("scroll", onScroll);
      window.removeEventListener("resize", onScroll);
    };
    // reduceMotion is a dependency so that toggling the OS setting mid-session
    // detaches the listener instead of leaving a scroll handler running against
    // a map that no longer reacts to it.
  }, [reduceMotion]);

  // The mile nearest the draw head, so the readout follows the line. Derived,
  // not stored — an effect here would add a render pass per scroll frame and
  // the value is a pure function of progress and miles. The 0.04 window means
  // the readout clears (falls back to the summary) when the head is between
  // markers rather than snapping to whichever one is marginally closer.
  const activeMile = useMemo(() => {
    let nearest: number | null = null;
    let best = 0.04;
    miles.forEach((mile, i) => {
      const delta = Math.abs(mile.at - progress);
      if (delta < best) {
        best = delta;
        nearest = i;
      }
    });
    return nearest;
  }, [progress, miles]);

  const dashOffset = pathLength * (1 - progress);
  const fundedCount = miles.filter((m) => m.status === "funded").length;
  const active = activeMile === null ? null : miles[activeMile];
  const activeIsPast = active !== null && active.at <= progress;

  return (
    <section
      ref={sectionRef}
      className={cn("relative overflow-hidden bg-ink py-20 text-off-white sm:py-28", className)}
    >
      <div className="mx-auto max-w-6xl px-4 sm:px-6">
        <div className="max-w-2xl">
          <p className="text-sm font-semibold uppercase tracking-[0.2em] text-bronze-light">
            The Journey
          </p>
          <h2 className="mt-2 text-balance font-display text-3xl font-semibold uppercase tracking-tight sm:text-4xl">
            Seventy Miles, Drawn By You
          </h2>
          <p className="mt-4 text-base leading-relaxed text-off-white/75">
            Every point on this line is a mile of the Chattanooga race. Scroll to ride it — each
            marker lights up as the road reaches it, and the line fills in as miles get funded.
          </p>
        </div>

        <div className="mt-12 grid gap-8 lg:grid-cols-[1.6fr_1fr] lg:items-center lg:gap-12">
          <div className="relative">
            <svg
              viewBox={`0 0 ${VIEWBOX} ${VIEWBOX}`}
              className="h-auto w-full overflow-visible"
              aria-hidden="true"
              focusable="false"
            >
              {/* Base route: always visible so the shape is legible before drawing. */}
              <path
                d={ROUTE_D}
                fill="none"
                stroke="currentColor"
                className="text-off-white/15"
                strokeWidth={1.4}
                strokeLinecap="round"
              />
              {/* Drawn portion. */}
              <path
                data-route-line
                d={ROUTE_D}
                fill="none"
                stroke="currentColor"
                className="text-bronze"
                strokeWidth={1.4}
                strokeLinecap="round"
                strokeDasharray={pathLength}
                strokeDashoffset={dashOffset}
                style={{ transition: "stroke-dashoffset 120ms linear" }}
              />

              {miles.map((mile, i) => {
                const point = samplePath(ROUTE_D, mile.at);
                const reached = mile.at <= progress;
                const isActive = i === activeMile;
                const radius = STATUS_RADIUS[mile.status];
                return (
                  <g
                    key={`${mile.at}-${i}`}
                    className="transition-opacity duration-300"
                    opacity={reached ? 1 : 0.45}
                  >
                    {isActive && (
                      <circle
                        cx={point.x}
                        cy={point.y}
                        r={radius + 2.4}
                        className="fill-bronze/25"
                      />
                    )}
                    <circle
                      cx={point.x}
                      cy={point.y}
                      r={radius}
                      className={cn(
                        "transition-colors duration-300",
                        mile.status === "funded"
                          ? "fill-bronze"
                          : reached
                            ? "fill-bronze/50"
                            : "fill-off-white/25",
                      )}
                    />
                  </g>
                );
              })}
            </svg>

            {/* Readout — the accessible equivalent of the graphic. */}
            <div
              className="mt-6 min-h-[5.5rem] rounded-sm border border-off-white/15 bg-off-white/5 p-4"
              aria-live="polite"
            >
              {active ? (
                <>
                  <p className="text-xs font-semibold uppercase tracking-widest text-bronze-light">
                    Mile {active.number} {activeIsPast ? "· behind you" : "· ahead"}
                  </p>
                  <p className="mt-1 font-display text-lg font-semibold uppercase tracking-wide">
                    {active.dedication ?? (active.status === "funded" ? "Funded" : "Open for a dedication")}
                  </p>
                  <p className="mt-1 text-sm text-off-white/70">
                    <CountUpNumber value={active.raised} formatter={(n) => `$${Math.round(n).toLocaleString()}`} />{" "}
                    of ${active.goal.toLocaleString()} raised
                  </p>
                </>
              ) : (
                <p className="text-sm text-off-white/70">
                  {fundedCount} of {miles.length} miles funded.
                </p>
              )}
            </div>
          </div>

          <div>
            <p className="text-xs font-semibold uppercase tracking-widest text-bronze-light">
              Progress
            </p>
            {/* Not a CountUpNumber: this value is driven by scroll, so the
                component's 1200ms rAF would restart every frame and trail the
                line. Scroll-linked numbers have to render synchronously. */}
            <p className="mt-2 font-display text-4xl font-semibold tabular-nums">
              {Math.round(progress * 100)}%
            </p>
            <p className="mt-1 text-sm text-off-white/70">of the route drawn</p>

            <dl className="mt-8 space-y-3 text-sm">
              <div className="flex items-baseline justify-between gap-4 border-b border-off-white/10 pb-3">
                <dt className="text-off-white/70">Miles funded</dt>
                <dd className="font-display text-lg font-semibold tabular-nums">
                  {fundedCount} / {miles.length}
                </dd>
              </div>
              <div className="flex items-baseline justify-between gap-4 border-b border-off-white/10 pb-3">
                <dt className="text-off-white/70">Raised</dt>
                <dd className="font-display text-lg font-semibold tabular-nums">
                  <CountUpNumber value={totalRaised} formatter={(n) => `$${Math.round(n).toLocaleString()}`} />
                </dd>
              </div>
              <div className="flex items-baseline justify-between gap-4">
                <dt className="text-off-white/70">Goal</dt>
                <dd className="font-display text-lg font-semibold tabular-nums">
                  ${goal.toLocaleString()}
                </dd>
              </div>
            </dl>
          </div>
        </div>
      </div>
    </section>
  );
}
