import Link from "next/link";
import { Container } from "@/components/shared/container";
import { requireAdminUser } from "@/lib/supabase/require-admin";
import { createAdminClient } from "@/lib/supabase/admin";
import { importFlagshipsAction, markFeedbackReviewedAction, updateNavigationRequestAction, updateResourceAction } from "./actions";

export default async function ResourceAdminPage() {
  await requireAdminUser(); const admin = createAdminClient();
  const [records, requests, feedback] = await Promise.all([
    admin.from("resource_records").select("id,name,verification_status,is_active,last_verified_at,why_included,faith_based").order("name"),
    admin.from("resource_navigation_requests").select("*").order("created_at", { ascending: false }).limit(50),
    admin.from("resource_feedback").select("*").eq("reviewed", false).order("created_at", { ascending: false }).limit(50),
  ]);
  return <Container className="max-w-6xl py-16"><Link href="/admin" className="text-sm font-semibold uppercase text-charcoal-light">← Back to overview</Link><div className="mt-4 flex flex-wrap items-center justify-between gap-4"><div><h1 className="font-display text-2xl font-semibold uppercase text-ink">Resource Management</h1><p className="mt-1 text-sm text-charcoal-light">Structured records, navigator requests, and private outcome feedback.</p></div><form action={importFlagshipsAction}><button className="rounded-sm bg-bronze-text px-5 py-3 text-xs font-semibold uppercase tracking-wide text-off-white">Import 32 flagships</button></form></div>
  <section className="mt-10"><h2 className="font-display text-lg font-semibold uppercase">Resource records ({records.data?.length ?? 0})</h2>{records.error && <p className="mt-3 text-sm text-red-700">Could not load resource records. Apply the resource migrations first.</p>}<div className="mt-3 grid gap-3 sm:grid-cols-2">{records.data?.map((r) => <form action={updateResourceAction} key={r.id} className="space-y-3 border border-ink/10 p-4 text-sm"><input type="hidden" name="id" value={r.id}/><strong>{r.name}</strong><p className="text-xs text-charcoal-light">Last checked: {r.last_verified_at ?? "Not dated"}</p><select name="verification_status" defaultValue={r.verification_status} className="w-full border border-ink/20 bg-off-white p-2"><option value="verified">Verified</option><option value="reviewed">Reviewed</option><option value="community-recommended">Community recommended</option><option value="pending-review">Pending review</option><option value="information-incomplete">Information incomplete</option></select><label className="block text-xs font-semibold uppercase tracking-wide text-charcoal-light">Faith affiliation<select name="faith_based" defaultValue={r.faith_based === true ? "yes" : r.faith_based === false ? "no" : "unknown"} className="mt-1 w-full border border-ink/20 bg-off-white p-2 text-sm normal-case tracking-normal text-ink"><option value="unknown">Unknown</option><option value="yes">Faith-based</option><option value="no">Not faith-based</option></select></label><textarea name="why_included" defaultValue={r.why_included ?? ""} rows={3} aria-label={`Why ${r.name} is included`} className="w-full border border-ink/20 bg-off-white p-2"/><label className="flex items-center gap-2"><input type="checkbox" name="is_active" defaultChecked={r.is_active}/> Active publicly</label><button className="text-xs font-semibold uppercase text-bronze">Save resource</button></form>)}</div></section>
  <section className="mt-10"><h2 className="font-display text-lg font-semibold uppercase">Ask For the 22 ({requests.data?.length ?? 0})</h2><div className="mt-3 space-y-3">{requests.data?.map((r) => <article key={r.id} className="border border-ink/10 p-5"><p className="text-sm font-semibold">{r.population} · {r.state || "No state"} · {r.email}</p><p className="mt-2 text-sm text-charcoal-light">{r.need}</p><form action={updateNavigationRequestAction} className="mt-3 flex gap-2"><input type="hidden" name="id" value={r.id}/><select name="status" defaultValue={r.status} className="border border-ink/20 bg-off-white px-3 py-2 text-xs"><option>new</option><option>in-progress</option><option>resolved</option><option>closed</option></select><button className="text-xs font-semibold uppercase text-bronze">Update</button></form></article>)}</div></section>
  <section className="mt-10"><h2 className="font-display text-lg font-semibold uppercase">Unreviewed feedback ({feedback.data?.length ?? 0})</h2><div className="mt-3 space-y-3">{feedback.data?.map((r) => <article key={r.id} className="border border-ink/10 p-5 text-sm"><strong>{r.resource_name}</strong><p className="mt-1 text-charcoal-light">Helpful: {r.helpful ? "Yes" : "No"} · Contacted: {r.contacted} · Connected: {r.connection}</p>{r.note && <p className="mt-2">{r.note}</p>}<form action={markFeedbackReviewedAction} className="mt-3"><input type="hidden" name="id" value={r.id}/><button className="text-xs font-semibold uppercase text-bronze">Mark reviewed</button></form></article>)}</div></section></Container>;
}
