"use client";

/* eslint-disable react-hooks/refs -- useFormSubmit intentionally returns a forwarded widget ref, matching the established site form pattern. */

import { useState } from "react";
import { HoneypotField, FormError, FormSuccess, FormSubmitButton, FORM_CONTROL_CLASS_COMPACT } from "@/components/forms/form-parts";
import { TurnstileWidget } from "@/components/forms/turnstile-widget";
import { useFormSubmit } from "@/components/forms/use-form-submit";
import { resourceFeedbackSchema, resourceNavigationSchema } from "@/lib/validation/resource-support";

const Field = ({ label, name, required = false, children }: { label: string; name: string; required?: boolean; children?: React.ReactNode }) => <label className="block text-sm font-medium text-ink">{label}{required && <span aria-hidden="true"> *</span>}{children ?? <input name={name} required={required} className={`mt-2 ${FORM_CONTROL_CLASS_COMPACT}`} />}</label>;

export function AskForThe22Form() {
  const [open, setOpen] = useState(false);
  const form = useFormSubmit({ endpoint: "/api/resource-navigation", schema: resourceNavigationSchema, buildPayload: (d) => ({ seekingFor: String(d.get("seekingFor") ?? ""), population: String(d.get("population") ?? ""), state: String(d.get("state") ?? ""), need: String(d.get("need") ?? ""), priorities: String(d.get("priorities") ?? ""), privacyConcerns: String(d.get("privacyConcerns") ?? ""), avoid: String(d.get("avoid") ?? ""), email: String(d.get("email") ?? "") }) });
  if (!open) return <div className="rounded-sm border border-ink/10 bg-off-white p-6"><p className="text-xs font-semibold uppercase tracking-widest text-bronze-text">Optional human help</p><div className="mt-2 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-display text-xl font-bold uppercase text-ink">Still not sure?</h2><p className="mt-1 max-w-2xl text-sm leading-relaxed text-charcoal-light">Ask us to identify a few options after you&apos;ve tried the directory. Do not include medical records or diagnoses.</p></div><button type="button" onClick={() => setOpen(true)} data-analytics-event="ask_forthe22_started" className="min-h-11 shrink-0 rounded-sm border border-ink/20 px-5 py-3 text-sm font-semibold uppercase tracking-wide text-ink hover:bg-ink/5">Ask For the 22</button></div></div>;
  if (form.status === "success") return <FormSuccess title="Request received">We&apos;ll review it and respond using the email you provided.</FormSuccess>;
  return <form onSubmit={form.handleSubmit} className="space-y-5 rounded-sm border border-ink/10 bg-sand-light p-6 sm:p-8" aria-busy={form.status === "submitting"}><HoneypotField id="companyWebsite"/><div><p className="text-xs font-semibold uppercase tracking-widest text-bronze-text">Ask For the 22</p><h2 className="mt-2 font-display text-2xl font-bold uppercase text-ink">Help us understand the need</h2><p className="mt-2 text-xs text-charcoal-light"><span aria-hidden="true">*</span> Required fields</p></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Who are you seeking help for?" name="seekingFor" required/><Field label="Veteran, first responder, family, or other?" name="population" required/><Field label="State (optional)" name="state"/><Field label="Email" name="email" required><input type="email" name="email" required className={`mt-2 ${FORM_CONTROL_CLASS_COMPACT}`}/></Field></div><Field label="What are you trying to solve?" name="need" required><textarea name="need" required rows={3} className={`mt-2 ${FORM_CONTROL_CLASS_COMPACT}`}/></Field><Field label="What matters most when choosing support?" name="priorities"/><Field label="Any privacy or employment concerns?" name="privacyConcerns"/><Field label="Anything you definitely do not want?" name="avoid"/><p className="text-xs leading-relaxed text-charcoal-light">We use this information only to respond to your request. Do not submit emergency information; call 911 or use the crisis resources above when immediate help is needed.</p><TurnstileWidget ref={form.turnstileRef} action="resource_navigation" onToken={form.setTurnstileToken}/><FormError message={form.status === "error" ? form.errorMessage : null}/><FormSubmitButton disabled={form.submitDisabled} submitting={form.status === "submitting"} idleLabel="Send request" data-analytics-event="ask_forthe22_submitted" /></form>;
}

export function ResourceFeedbackForm() {
  const form = useFormSubmit({ endpoint: "/api/resource-feedback", schema: resourceFeedbackSchema, buildPayload: (d) => ({ resourceName: String(d.get("resourceName") ?? ""), helpful: String(d.get("helpful") ?? ""), contacted: String(d.get("contacted") ?? ""), connection: String(d.get("connection") ?? ""), note: String(d.get("note") ?? "") }) });
  if (form.status === "success") return <FormSuccess title="Thank you">Your feedback is private and will help us review the directory.</FormSuccess>;
  return <form onSubmit={form.handleSubmit} className="space-y-4" aria-busy={form.status === "submitting"}><HoneypotField id="feedbackCompanyWebsite"/><div className="grid gap-4 sm:grid-cols-2"><Field label="Resource name" name="resourceName" required/><Field label="Was the information helpful?" name="helpful" required><select name="helpful" required className={`mt-2 ${FORM_CONTROL_CLASS_COMPACT}`}><option value="">Choose</option><option value="yes">Yes</option><option value="no">No</option></select></Field><Field label="Did you contact the organization?" name="contacted" required><select name="contacted" required className={`mt-2 ${FORM_CONTROL_CLASS_COMPACT}`}><option value="not-yet">Not yet</option><option value="yes">Yes</option><option value="prefer-not-to-say">Prefer not to say</option></select></Field><Field label="Were you able to connect?" name="connection" required><select name="connection" required className={`mt-2 ${FORM_CONTROL_CLASS_COMPACT}`}><option value="not-applicable">Not applicable</option><option value="yes">Yes</option><option value="no">No</option><option value="waiting">Still waiting</option><option value="prefer-not-to-say">Prefer not to say</option></select></Field></div><Field label="Optional note" name="note"/><TurnstileWidget ref={form.turnstileRef} action="resource_feedback" onToken={form.setTurnstileToken}/><FormError message={form.status === "error" ? form.errorMessage : null}/><FormSubmitButton disabled={form.submitDisabled} submitting={form.status === "submitting"} idleLabel="Send private feedback" /></form>;
}
